[build]
  functions = "src/functions/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
